[package]
description = "An attribute macro to specify a path to a module dynamically."
license = "MIT/Apache-2.0"
name = "dynpath"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = {version = "1", features = ["full"]}
